services:
  # FastAPI (Python)
  - type: web
    name: medmitra-fastapi
    env: docker
    rootDir: .
    dockerfilePath: backend/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true

  # Node backend (Twilio, kiosk, etc.)
  - type: web
    name: medmitra-node
    env: docker
    rootDir: .
    dockerfilePath: node-backend/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true

  # Frontend (Vite)
  - type: web
    name: medmitra-frontend
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      # Ensure a modern Node for the Vite build
      - key: NODE_VERSION
        value: 20
      # Inject backend URLs at build time
      - key: VITE_API_BASE
        fromService:
          name: medmitra-fastapi
          type: web
          property: url
      - key: VITE_VOICE_BASE
        fromService:
          name: medmitra-node
          type: web
          property: url
