services:
  # FastAPI (Python)
  - type: web
    name: medmitra-fastapi
    env: docker
    rootDir: .
    dockerfilePath: backend/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true

  # Node backend (Twilio, kiosk, etc.)
  - type: web
    name: medmitra-node
    env: docker
    rootDir: .
    dockerfilePath: node-backend/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true

  # Frontend (Vite)
  - type: web
    name: medmitra-frontend
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    # optional: ensure modern Node for the Vite build
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
