services:
  # FastAPI (Python)
  - type: web
    name: medmitra-fastapi
    env: docker
    rootDir: .
    dockerfilePath: backend/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: FRONTEND_URL
        value: ""         # set later to your frontend URL if you want strict CORS
      - key: CORS_EXTRA
        value: ""         # comma-separated origins if needed

  # Node backend
  - type: web
    name: medmitra-node
    env: docker
    rootDir: .
    dockerfilePath: node-backend/Dockerfile
    plan: free
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: ALLOWED_ORIGIN
        value: ""         # comma-separated origins if needed

  # Frontend (Vite)
  - type: web
    name: medmitra-frontend
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "20"
      # set these two AFTER the backends are live:
      - key: VITE_API_BASE
        value: ""
      - key: VITE_VOICE_BASE
        value: ""
    autoDeploy: true
